language: node_js
node_js:
  - "10"

script: npm run build
branches:
  only:
    - src

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  local-dir: public
  target-branch: master
  on:
    branch: src
